logging:
  config: classpath:logback.xml
  #path: d:/logs/
server:
  port: 8700
spring:
  application:
    name: cr-cloud-zuul
  # 数据源支持 也支持密文 用户名密码
  datasource:
    url: jdbc:oracle:thin:@//10.101.96.2:1521/crmpdb
    username: F1_HRA
    password: F1_HRA$CR123
    driver-class-name: oracle.jdbc.OracleDriver
    # Alibaba druid 连接池支持
    druid.initial-size: 1
    druid.min-idle: 1
    druid.max-active: 10
    druid.test-on-borrow: true
    druid.stat-view-servlet.allow: true 
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update 
  # sso的redis 缓存，暂时用65.5 后续着生产环境变动改变缓存位置
  redis:
    host: 10.101.65.5
    password: 123456
    port: 8380
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
eureka:
  #instance:
    # 每隔10s发送一次心跳
    #leaseRenewalIntervalInSeconds: 10
    # 告知服务端10秒还未收到心跳的话，就将该服务移除列表
    #leaseExpirationDurationInSeconds: 10
  client:
    #表示eureka client间隔多久去拉取服务注册信息,默认为30秒
    registry-fetch-interval-seconds: 10
    serviceUrl:
      defaultZone: http://admin:admin@10.100.96.14:8761/eureka
logging.level:
  root: info
  org.springframework: info
zuul:
  #设置参数Encoding
  forceOriginalQueryStringEncoding: true
 # routes:
  #  service-A:
   #   path: /**
    #  serviceId: api
  max:
    host:
      connections: 500
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    maxPerRouteConnections : 10
    maxTotalConnections : 200
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 300000 
  ConnectTimeout: 300000 
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
management:
     security:
        enabled: false
      
      